included:
  - Claudiator

excluded:
  - Claudiator.xcodeproj
  - build
  - DerivedData

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - trailing_whitespace
  - todo

line_length:
  warning: 150
  error: 200

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 80

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - f
    - s
    - d
    - c

nesting:
  type_level: 2
  function_level: 3

reporter: "xcode"
