name: Claudiator
options:
  bundleIdPrefix: com.claudiator
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  Claudiator:
    type: application
    platform: iOS
    sources:
      - path: Claudiator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudiator.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Claudiator/Info.plist
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    entitlements:
      path: Claudiator/Claudiator.entitlements
      properties:
        aps-environment: development
